### ISSUE TITLE
1. Omit gradle folder- it contains gradle jar file. Should not be checked in repo

### ISSUE THREAD

**Issue by singhmanish3007** [neetidotexe/courier-service#1]
2.go for application.yml file instead of properties file. Enjoy beauty of yml over properties

**Comment by neetidotexe** [comment]
Started using application.yaml

**Comment by neetidotexe** [comment]
committing the gradle-wrapper.jar file into GitHub repository is a recommended practice for Java projects using Gradle. 
It makes sure all contributors are using same Gradle version, facilitating consistent and reliable builds across different environments.
